
debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    #클라우드용 설정
    url: ${JAWSDB_URL}
    password: ${JAWSDB_PASSWROD}
    username: ${JAWSDB_USERNAME}
    hikari:
      maximum-pool-size: 9
    config.activate.on-profile: heroku

    #로컬용 설정
#    url : jdbc:mysql://localhost:3306/board
#    username:  smh
#    password: alsgur0700!
    jpa.hibernate.ddl-auto: create
    sql.init.mode: always


    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  #servlet:
    #multipart:
      #location: "C:\\Users\\smh03\\Desktop"
      #max-file-size: 10MB
      #max-request-size: 50MB
      #enabled: true

  #클라우드용 설정
  config:
    activate:
      on-cloud-platform: heroku

custom:
  path:
    #클라우드용 설정
    upload-files: /tmp/
    #로컬용 설정
    #upload-files: C:\\Users\\smh03\\Desktop\\

server:
  port=${port:8080}: